/**
 * Sidebar links per role. Paths are under /dashboard (protected).
 * icon: key used to pick an icon in Sidebar (dashboard, users, file, calendar, settings, message).
 */
export const sidebarLinks = {
  admin: [
    { label: 'Manage FYP sessions', path: '/dashboard/admin/manage-sessions', icon: 'calendar' },
    { label: 'Manage events', path: '/dashboard/admin/manage-events', icon: 'calendar' },
    { label: 'Manage students', path: '/dashboard/admin/manage-students', icon: 'users' },
    { label: 'Manage Supervisors', path: '/dashboard/admin/manage-supervisors', icon: 'users' },
    { label: 'Manage evaluators', path: '/dashboard/admin/manage-evaluators', icon: 'users' },
    { label: 'Manage domains', path: '/dashboard/admin/manage-domains', icon: 'file' },
    { label: 'Manage Evaluator Panels', path: '/dashboard/admin/evaluator-panels', icon: 'users' },
    { label: 'All FYP sessions', path: '/dashboard/admin/all-sessions', icon: 'calendar' },
    { label: 'All registered domains', path: '/dashboard/admin/all-domains', icon: 'file' },
    { label: 'All registered supervisors', path: '/dashboard/admin/all-supervisors', icon: 'users' },
    { label: 'All registered evaluators', path: '/dashboard/admin/all-evaluators', icon: 'users' },
    { label: 'Groups & Evaluation Panels (defense 1)', path: '/dashboard/admin/groups-defense1', icon: 'users' },
    { label: 'Groups and Evaluation Panels (defense 2)', path: '/dashboard/admin/groups-defense2', icon: 'users' },
    { label: 'Domains and supervisors', path: '/dashboard/admin/domains-supervisors', icon: 'file' },
    { label: 'Session policy', path: '/dashboard/admin/session-policy', icon: 'file' },
    { label: 'FYP resources', path: '/dashboard/admin/fyp-resources', icon: 'file' },
    { label: 'FYP Events', path: '/dashboard/admin/fyp-events', icon: 'calendar' },
    { label: 'Previous FYPs', path: '/dashboard/admin/previous-fyps', icon: 'file' },
    { label: 'Supervisor Allocation Status', path: '/dashboard/admin/supervisor-allocation', icon: 'users' },
    { label: 'Group Requests', path: '/dashboard/admin/group-requests', icon: 'file' },
    { label: 'Give Marks', path: '/dashboard/admin/give-marks', icon: 'file' },
  ],
  student: [
    { label: 'Chat homes', path: '/dashboard/student/chat-homes', icon: 'message' },
    { label: 'All domains', path: '/dashboard/student/all-domains', icon: 'file' },
    { label: 'Domains and supervisors', path: '/dashboard/student/domains-supervisors', icon: 'file' },
    { label: 'Session policy', path: '/dashboard/student/session-policy', icon: 'file' },
    { label: 'FYP resources', path: '/dashboard/student/fyp-resources', icon: 'file' },
    { label: 'FYP Events', path: '/dashboard/student/fyp-events', icon: 'calendar' },
    { label: 'Previous FYPs', path: '/dashboard/student/previous-fyps', icon: 'file' },
    { label: 'Register Group', path: '/dashboard/student/register-group', icon: 'users' },
    { label: 'Request Status', path: '/dashboard/student/request-status', icon: 'file' },
    { label: 'Complete FYP guide/lifecycle', path: '/dashboard/student/fyp-guide', icon: 'file' },
    { label: 'All Supervisor Meetings', path: '/dashboard/student/meetings', icon: 'calendar' },
    { label: 'Supervisor Allocation Status', path: '/dashboard/student/supervisor-allocation', icon: 'users' },
    { label: 'Groups & Evaluation Panels (defense 1)', path: '/dashboard/student/groups-defense1', icon: 'users' },
    { label: 'Groups and Evaluation Panels (defense 2)', path: '/dashboard/student/groups-defense2', icon: 'users' },
  ],
  supervisor: [
    { label: 'All domains', path: '/dashboard/supervisor/all-domains', icon: 'file' },
    { label: 'Domains and supervisors', path: '/dashboard/supervisor/domains-supervisors', icon: 'file' },
    { label: 'Session policy', path: '/dashboard/supervisor/session-policy', icon: 'file' },
    { label: 'FYP resources', path: '/dashboard/supervisor/fyp-resources', icon: 'file' },
    { label: 'FYP Events', path: '/dashboard/supervisor/fyp-events', icon: 'calendar' },
    { label: 'Create Meeting', path: '/dashboard/supervisor/create-meeting', icon: 'calendar' },
    { label: 'All Meetings', path: '/dashboard/supervisor/all-meetings', icon: 'calendar' },
    { label: 'Supervisor Allocation Status', path: '/dashboard/supervisor/allocation-status', icon: 'users' },
    { label: 'Group Requests', path: '/dashboard/supervisor/group-requests', icon: 'file' },
    { label: 'Groups and Evaluation Panels (defense 1)', path: '/dashboard/supervisor/groups-defense1', icon: 'users' },
    { label: 'Groups and Evaluation Panels (defense 2)', path: '/dashboard/supervisor/groups-defense2', icon: 'users' },
    { label: 'Give Marks', path: '/dashboard/supervisor/give-marks', icon: 'file' },
  ],
  evaluator: [
    { label: 'All domains', path: '/dashboard/evaluator/all-domains', icon: 'file' },
    { label: 'Domains and supervisors', path: '/dashboard/evaluator/domains-supervisors', icon: 'file' },
    { label: 'Session policy', path: '/dashboard/evaluator/session-policy', icon: 'file' },
    { label: 'FYP resources', path: '/dashboard/evaluator/fyp-resources', icon: 'file' },
    { label: 'FYP Events', path: '/dashboard/evaluator/fyp-events', icon: 'calendar' },
    { label: 'Groups and Evaluation Panels (defense 1)', path: '/dashboard/evaluator/groups-defense1', icon: 'users' },
    { label: 'Groups and Evaluation Panels (defense 2)', path: '/dashboard/evaluator/groups-defense2', icon: 'users' },
    { label: 'Assigned Groups', path: '/dashboard/evaluator/assigned-groups', icon: 'users' },
    { label: 'Give Marks', path: '/dashboard/evaluator/give-marks', icon: 'file' },
  ],
};
