/**
 * Sidebar links per role. Paths are under /dashboard (protected).
 * icon: key used to pick an icon in Sidebar (dashboard, users, file, calendar, settings, message).
 */
export const sidebarLinks = {
  admin: [
    { label: 'Create Evaluator Account', path: '/dashboard/admin/create-evaluator-account', icon: 'users' },
    { label: 'Create Student Account', path: '/dashboard/admin/create-student-account', icon: 'users' },
    { label: 'Create Supervisor Account', path: '/dashboard/admin/create-supervisor-account', icon: 'users' },
    { label: 'Manage FYP sessions', path: '/dashboard/manage-sessions', icon: 'calendar' },
    { label: 'Manage domains', path: '/dashboard/manage-domains', icon: 'file' },
    { label: 'Manage Supervisors', path: '/dashboard/manage-supervisors', icon: 'users' },
    { label: 'Manage evaluators', path: '/dashboard/manage-evaluators', icon: 'users' },
    { label: 'Manage students', path: '/dashboard/manage-students', icon: 'users' },
    { label: 'Domains and supervisors', path: '/dashboard/domains-supervisors', icon: 'file' },
    { label: 'Supervisor Allocation Status', path: '/dashboard/supervisor-allocation', icon: 'users' },
    { label: 'All registered domains', path: '/dashboard/all-domains', icon: 'file' },
    { label: 'All registered groups', path: '/dashboard/all-groups', icon: 'users' },
    { label: 'Group Requests', path: '/dashboard/admin/group-requests', icon: 'file' },
    { label: 'Create panels for D1', path: '/dashboard/create-panels-d1', icon: 'users' },
    { label: 'Panel assignment D1', path: '/dashboard/panel-assignment-d1', icon: 'users' },
    { label: 'Panels for D1', path: '/dashboard/panels-d1', icon: 'users' },
    { label: 'Create panels for D2', path: '/dashboard/create-panels-d2', icon: 'users' },
    { label: 'Panel assignment D2', path: '/dashboard/panel-assignment-d2', icon: 'users' },
    { label: 'Panels for D2', path: '/dashboard/panels-d2', icon: 'users' },
    { label: 'Give D1 marks', path: '/dashboard/give-d1-marks', icon: 'file' },
    { label: 'Give D2 marks', path: '/dashboard/give-d2-marks', icon: 'file' },
    { label: 'Create deadline', path: '/dashboard/create-deadline', icon: 'calendar' },
    { label: 'All deadlines', path: '/dashboard/all-deadlines', icon: 'calendar' },
    { label: 'All submissions', path: '/dashboard/all-submissions', icon: 'file' },
    { label: 'Session policy', path: '/dashboard/session-policy', icon: 'file' },
    { label: 'FYP resources', path: '/dashboard/fyp-resources', icon: 'file' },
    { label: 'FYP Events', path: '/dashboard/fyp-events', icon: 'calendar' },
    { label: 'Chat with FIA', path: '/dashboard/fia', icon: 'ai' },
  ],
  student: [
    { label: 'Chat rooms', path: '/dashboard/chat-rooms', icon: 'message' },
    { label: 'All domains', path: '/dashboard/all-domains', icon: 'file' },
    { label: 'Domains and supervisors', path: '/dashboard/domains-supervisors', icon: 'file' },
    { label: 'Session policy', path: '/dashboard/session-policy', icon: 'file' },
    { label: 'FYP resources', path: '/dashboard/fyp-resources', icon: 'file' },
    { label: 'FYP Events', path: '/dashboard/fyp-events', icon: 'calendar' },
    { label: 'Register Group', path: '/dashboard/register-group', icon: 'users' },
    { label: 'Request Status', path: '/dashboard/request-status', icon: 'file' },
    { label: 'Complete FYP guide/lifecycle', path: '/dashboard/fyp-guide', icon: 'file' },
    { label: 'All meetings', path: '/dashboard/all-meetings', icon: 'calendar' },
    { label: 'Supervisor Allocation Status', path: '/dashboard/supervisor-allocation', icon: 'users' },
    { label: 'Panels for D1', path: '/dashboard/panels-d1', icon: 'users' },
    { label: 'All registered groups', path: '/dashboard/all-groups', icon: 'users' },
    { label: 'All deadlines', path: '/dashboard/all-deadlines', icon: 'calendar' },
    { label: 'Chat with FIA', path: '/dashboard/fia', icon: 'ai' },
  ],
  supervisor: [
    { label: 'Chat rooms', path: '/dashboard/chat-rooms', icon: 'message' },
    { label: 'All domains', path: '/dashboard/all-domains', icon: 'file' },
    { label: 'Domains and supervisors', path: '/dashboard/domains-supervisors', icon: 'file' },
    { label: 'Session policy', path: '/dashboard/session-policy', icon: 'file' },
    { label: 'FYP resources', path: '/dashboard/fyp-resources', icon: 'file' },
    { label: 'FYP Events', path: '/dashboard/fyp-events', icon: 'calendar' },
    { label: 'Create Meeting', path: '/dashboard/create-meeting', icon: 'calendar' },
    { label: 'All Meetings', path: '/dashboard/all-meetings', icon: 'calendar' },
    { label: 'Supervisor Allocation Status', path: '/dashboard/supervisor-allocation', icon: 'users' },
    { label: 'Group Requests', path: '/dashboard/supervisor/group-requests', icon: 'file' },
    { label: 'My groups', path: '/dashboard/my-groups', icon: 'users' },
    { label: 'All registered groups', path: '/dashboard/all-groups', icon: 'users' },
    { label: 'Give D1 marks', path: '/dashboard/supervisor/give-d1-marks', icon: 'file' },
    { label: 'Give D2 marks', path: '/dashboard/supervisor/give-d2-marks', icon: 'file' },
    { label: 'Chat with FIA', path: '/dashboard/fia', icon: 'ai' },
  ],
  evaluator: [
    { label: 'All domains', path: '/dashboard/all-domains', icon: 'file' },
    { label: 'Domains and supervisors', path: '/dashboard/domains-supervisors', icon: 'file' },
    { label: 'Session policy', path: '/dashboard/session-policy', icon: 'file' },
    { label: 'FYP resources', path: '/dashboard/fyp-resources', icon: 'file' },
    { label: 'FYP Events', path: '/dashboard/fyp-events', icon: 'calendar' },
    { label: 'Complete FYP guide/lifecycle', path: '/dashboard/fyp-guide', icon: 'file' },
    { label: 'Panels for D1', path: '/dashboard/panels-d1', icon: 'users' },
    { label: 'Give D1 marks', path: '/dashboard/evaluator/give-d1-marks', icon: 'file' },
    { label: 'Give D2 marks', path: '/dashboard/evaluator/give-d2-marks', icon: 'file' },
    { label: 'Chat with FIA', path: '/dashboard/fia', icon: 'ai' },
  ],
};
